"""New

Revision ID: e40bcda1b128
Revises: c69edf96ce51
Create Date: 2023-11-25 22:57:19.493751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40bcda1b128'
down_revision: Union[str, None] = 'c69edf96ce51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'servers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servers', type_='unique')
    # ### end Alembic commands ###
